DROP TABLE CUSTOMERS IF EXISTS;   
CREATE TABLE CUSTOMERS (   
	CUSTOMER_ID VARCHAR(25) PRIMARY KEY,  
	NAME VARCHAR(50),      
	ADDRESS  VARCHAR(250),  
	NUMBER_OF_ORDERS BIGINT,            
	VALID BOOLEAN
	);